//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Girist.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_GIRIST_DIALOG               102
#define IDS_LIB_OVERWRITE               102
#define IDS_APP_NAME                    103
#define IDS_LIB_CHANGEPATH              104
#define IDS_SVAE_CHANGE                 105
#define IDS_SVAE_CHANGE2                106
#define IDS_SVAE_UNTITLED               106
#define IDS_SVAE_SUCCEED                107
#define IDS_BUILD_CANCEL                108
#define IDS_THREAD_CREATE_FAIL          109
#define IDS_GIRIST_RESTART              110
#define IDS_LIB_LOAD_ERR                111
#define IDS_FAIL_INIT_CONTROL           112
#define IDS_IRIS_AUTHEN_OK              113
#define IDS_IRIS_AUTHEN_FAIL            114
#define IDS_IRIS_AUTHEN_THRESH          115
#define IDS_IRIS_IDENTIFY_OK            116
#define IDS_IRIS_IDENTIFY_FAIL          117
#define IDS_LIB_NOOK                    118
#define IDS_LOCATION_FAIL               119
#define IDS_IRIS_DISTANCE_2             120
#define IDS_IRIS_DISTANCE_2_FAIL        121
#define IDR_TOOLBAR                     130
#define IDD_COMMENT                     136
#define IDD_TAB_IRIS                    137
#define IDD_TAB_TREE                    138
#define IDD_BUILD_DLG                   140
#define ID_INDICATOR_TIME               141
#define IDB_GRUSOFT                     141
#define ID_INDICATOR_SEARCH             142
#define ID_INDICATOR_CORE               142
#define IDD_DISTRI_DLG                  142
#define IDD_PROGRESS_DLG                143
#define IDR_MAINFRAME                   143
#define IDI_ICON1                       144
#define IDC_TAB1                        1000
#define IDC_TAB_PROJ                    1000
#define IDC_EDIT1                       1002
#define IDC_ED_COMMENT                  1002
#define IDC_EDIT_NOTE                   1002
#define ID_CB_MODE                      1003
#define IDC_TAB2                        1003
#define IDC_EDIT_P                      1003
#define IDC_TAB_SOURCE                  1003
#define IDC_TAB3                        1004
#define IDC_EDIT3                       1004
#define IDC_EDIT_S                      1004
#define IDC_TAB_TARGET                  1004
#define IDC_ED_WAVELEN                  1004
#define IDC_STATIC_NORMAL               1005
#define IDC_STATIC_EYE                  1006
#define IDC_TREE1                       1007
#define IDC_CUSTOM_EYE                  1008
#define IDC_CUSTOM_NORMAL               1009
#define IDC_ST_INFO                     1011
#define IDC_PROGRESS1                   1012
#define IDC_LIST2                       1014
#define IDC_BT_CHANGEPATH               1015
#define IDC_CUSTOM1                     1016
#define IDC_CUSTOM_DISTRI               1016
#define IDC_ST_LIBPATH                  1017
#define IDC_ED_LIBPATH                  1018
#define IDC_ST_DISTRI_INFO              1019
#define IDC_BT_DISTRI                   1020
#define IDC_GROUP_BUILD                 1021
#define IDC_GROUP_DISTRIBUTION          1022
#define IDC_CHECK1                      1023
#define IDC_BT_SWITCH                   1024
#define IDC_SLIDER1                     1025
#define IDC_ED_DCRIMI                   1028
#define IDC_ED_SHIFT                    1030
#define IDC_CUSTOM_ROC                  1031
#define IDC_SYSLINK1                    1033
#define IDC_EDIT_SEP                    1034
#define IDC_CB_LEVEL                    1036
#define IDC_ST_SEP                      1037
#define IDC_BMP_LOG                     1038
#define IDC_BMP_LOGO                    1039
#define IDI_GIRIST                      1040
#define IDC_BUTTON1                     1041
#define IDC_BUTTON2                     1042
#define ID_BUTTON32771                  32771
#define ID_BUTTON32772                  32772
#define ID_BUTTON32773                  32773
#define ID_LIB_OPEN                     32773
#define ID_SEL_MODE                     32774
#define ID_BUTTON32775                  32775
#define ID_BUTTON32776                  32776
#define ID_BUTTON32777                  32777
#define ID_LIB_INFO                     32777
#define ID_BUTTON32778                  32778
#define ID_LIB_DISTRI                   32778
#define ID_BUTTON32779                  32779
#define ID_LIB_BUILD                    32779
#define ID_BUTTON32780                  32780
#define ID_LIB_CREATE                   32781
#define ID_LIB_SAVE                     32782
#define ID_BUTTON32787                  32787
#define ID_TOOL_HELP                    32789
#define ID_IRIS_AUTHEN                  32790
#define ID_IRIS_IDENTIFY                32791
#define ID_BUTTON32792                  32792
#define ID_LIB_CLOSE                    32792

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        145
#define _APS_NEXT_COMMAND_VALUE         32793
#define _APS_NEXT_CONTROL_VALUE         1043
#define _APS_NEXT_SYMED_VALUE           102
#endif
#endif
